spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**

        - id: employee-route
          uri: http://localhost:8080
          predicates:
            - Path=/employees/**
          filters:
            - name: CircuitBreaker
              args:
                name: EMPLOYEE-SERVICE
                fallbackUri: forward:/employeeServiceFallback

        - id: address-route
          uri: http://localhost:8081
          predicates:
            - Path=/addresses/**
          filters:
            - name: CircuitBreaker
              args:
                name: ADDRESS-SERVICE
                fallbackUri: forward:/addressServiceFallback

resilience4j:
  circuitbreaker:
    instances:
      EMPLOYEE-SERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 6s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED

      ADDRESS-SERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 6s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED

  timelimiter:
    instances:
      EMPLOYEE-SERVICE:
        timeoutDuration: 5s
      ADDRESS-SERVICE:
        timeoutDuration: 5s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

server:
  port: 9090

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka